jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${ENCRYPTION_PASSWORD:}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


telegram:
  api-url: https://api.telegram.org/
  bot-name: writeEnglishcorrectly_bot
  bot-token: ENC(yc7BRAEc850e+1Eodf435RNBxigOJgrdpnjZGtMwkHtqRHiSK9Vdl3BhkhpeIeyPX4cvINcurGU=)
  ownerID: 994138843
  webhook-path: https://4143-104-236-95-26.ngrok-free.app/whreception  #"Адрес вебхука - локально получаем от ngrok"
server:
  port: 5000
files:
  incoming: incoming
  outgoing: outgoing
ffmpeg:
  path: /home/progforce/TelegBotOnWHook/src/main/resources/ffmpeg
schedule:
  cron:
    delete-temp-files: 0 */10 * ? * *        #крон для удаления временных файлов
message:
  start:
    picture-file-id:   #"Telegram-идентификатор картинки, отправляемой пользователю в ответ на команду /start"
    text:  Hi! #"ответ на команду /start"
    picture-file-path: Ein2.jpg
  too-big-voice:
    text: voice message time limit = 10 minutes
  illegal-message:
    text: I'll think about it    #"текст сообщения в ответ на отправку любого типа сообщений, кроме /start и голосовых"
  wtf:
    text: something went wrong (Internal Server Error)


spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/infoBot
    username: postgres
    password: ENC(meZs5HRHLgkbTC6tnK5Yur/vzTwczaNM)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



