jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${ENCRYPTION_PASSWORD:}
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


telegram:
  api-url: https://api.telegram.org/
  bot-name: writeEnglishcorrectly_bot
  bot-token: ENC(yc7BRAEc850e+1Eodf435RNBxigOJgrdpnjZGtMwkHtqRHiSK9Vdl3BhkhpeIeyPX4cvINcurGU=)
  ownerID: 994138843
  webhook-path: "Адрес вебхука - локально получаем от ngrok"
server:
  port: 5000
files:
  incoming: "префикс названия временных файлов голосовых сообщений - нужен, чтобы найти потом эти временные файлы и удалить их"
  outgoing: "префикс названия временных файлов .mp3 - нужен, чтобы найти потом эти временные файлы и удалить их"
ffmpeg:
  path: ffmpeg
schedule:
  cron:
    delete-temp-files: 0 */10 * ? * *        //крон для удаления временных файлов
message:
  start:
    picture-file-id: "Telegram-идентификатор картинки, отправляемой пользователю в ответ на команду /start"
    text: "текст сообщения в ответ на команду /start"
  too-big-voice:
    text: voice message time limit = 10 minutes
  illegal-message:
    text: "текст сообщения в ответ на отправку любого типа сообщений, кроме /start и голосовых"
  wtf:
    text: something went wrong (Internal Server Error)


spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/infoBot
    username: postgres
    password: ENC(meZs5HRHLgkbTC6tnK5Yur/vzTwczaNM)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



